Captian Blog/Blog/urls.py
#!/usr/bin/python
# -*- coding:utf-8 -*-
from django.conf.urls import url, include
from . import views

urlpatterns = [
    # 主页
    url(r'^$', views.index, name='index'),
    # 详情页
    url(r'^post/(?P<pk>[0-9]+)/$', views.detail, name='detail'),
    #文章归档
    url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.Archives, name='Archives'),
    #文章主题
    url(r'^category/(?P<pk>[0-9]+)/$', views.categroy_detail, name='category'),
    # 写文章
    url(r'^new_article/$', views.new_article, name='new_article'),
    #文章草稿箱
    url(r'^drafts/$', views.article_draft_list, name='article_draft_list'),
    #编辑文章
    url(r'^edit_article/(?P<pk>[0-9]+)/$', views.edit_article, name='edit_article'),
    #删除文章
    url(r'^article_remove/(?P<pk>[0-9]+)/$', views.article_remove, name='article_remove'),
    #全文搜索
    url(r'^search/', include('haystack.urls')),
]

Captian Blog/Web/urls.py
#!/usr/bin/python
# -*- coding:utf-8 -*-
"""Web URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.10/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url, include
#from django.contrib import admin
from extra_apps import xadmin


urlpatterns = [
    #url(r'^admin/', admin.site.urls),
    url(r'^xadmin/', include(xadmin.site.urls), name='xadmin'),
    url(r'^user/', include('user.urls', namespace='user')),
    url(r'', include('Blog.urls', namespace='Blog')),
]

Captian Blog/Blog/forms.py
from django import forms
from .models import Comments, Article


class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ['categroy', 'title', 'body', 'status', 'topped']


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comments
        fields = ['name','comment_body']

Captian Blog/Blog/views.py
#!/usr/bin/python
# -*- coding:utf-8 -*-
from Blog.models import Article ,Comments ,Categroy
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404
from django.db.models import Count
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from .forms import ArticleForm, CommentForm
import markdown


def index(request):
    """
    主页信息返回
    """
    post_list = Article.objects.filter(status='published')
    return render(request, 'blog/index.html',context={'post_list': post_list})


def article_draft_list(request):
    '''文章草稿箱'''
    draft_lists = Article.objects.filter(status='draft').order_by('-created')
    context = {'draft_lists': draft_lists}
    return render(request, 'blog/article_draft_list.html', context)


def Archives(request,year,month):
    post_list = Article.objects.filter(created__year=year,
                                        created__month=month,)
    return render(request, 'blog/index.html', context= {'post_list': post_list})


def Category(request, pk):
    """
    显示对应主题所有文章
    """
    cate = get_object_or_404(Category, pk=pk)
    post_list = Categroy.objects.filter(theme=cate).filter(status='published')
    context={'post_list': post_list}
    return render(request, 'blog/index.html', context)


def categroy_detail(request, pk):
    '''分类标签文章详情'''
    article_list = Categroy.objects.get(pk=pk)
    articles = article_list.article_set.filter(status='published').order_by('-created')
    context = {'article_list': article_list,'articles': articles}

    return render(request, 'blog/categroy_detail.html', context )


def detail(request, pk):
    """
    文章详情页
    """
    article = get_object_or_404(Article, pk=pk)
    body = Article.objects.get(pk=pk)
    ''' 添加评论'''
    comments = article.comments.filter(active=True)
    #添加了一个查询集（QuerySet）来获取这个帖子所有有效的评论，通过参数过滤所有已经发布过的
    new_comment = None
    # 定义一个变量名为new_comment 及为新的评论 为 空

    if request.method == 'POST':
         # 如果是通过POST请求，我们使用提交的数据新建一条评论
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # 用is_valid()方法验证这些数据去实例化表单，如果表单通过验证，我们会做以下的操作：
            new_comment = comment_form.save(commit=False)
            '''
            通过调用表单的save()方法创建一个新的Comment对象，参数执行使对象无法立即保存到数据库中。
            注意save()方法是给ModelForm用的，而不是给Form实例用的
            '''
            new_comment.article = article
             #为刚创建的评论分配到当前的帖子
            new_comment.save()
            # 再次执行保存，这次是保存到数据库中的
    else:
        #通过GET请求被加载的，那么我们用comment_fomr = commentForm()来创建一个表单实例。
        comment_form = CommentForm()
    return render(request, 'blog/detail.html',
                    {
                    'article': article,
                    'comments': comments,
                    'body': body,
                    'comment_form': comment_form})


def new_article(request):
    '''写文章'''
    if request.method != "POST":
        form = ArticleForm()
    else:
        form = ArticleForm(data=request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            #提交后跳转到index页面
            return HttpResponseRedirect(reverse('Blog:index'))
    context = {'form': form}
    return render(request, 'blog/new_article.html', context)


def edit_article(request, pk):
    '''编辑文章'''
    article = get_object_or_404(Article, pk=pk)
    body = Article.objects.get(pk=pk)

    if request.method != "POST":
        form = ArticleForm(instance=body)
    else:
        form = ArticleForm(instance=body, data=request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            #提交后跳转到index页面
            return HttpResponseRedirect(reverse('Blog:index'))

    context = {'article': article, 'form': form}
    return render(request, 'blog/edit_article.html', context)


def article_remove(request, pk):
    article = get_object_or_404(Article, pk=pk)
    article.delete()
    return HttpResponseRedirect(reverse('Blog:index'))

Captian Blog/extra_apps/xadmin/views/detail.py
from __future__ import absolute_import
import copy

from crispy_forms.utils import TEMPLATE_PACK
from django import forms
from django.contrib.contenttypes.models import ContentType
from django.core.exceptions import PermissionDenied, ObjectDoesNotExist
from django.db import models
from django.forms.models import modelform_factory
from django.http import Http404
from django.template import loader
from django.template.response import TemplateResponse
from django.utils import six
from django.utils.encoding import force_text, smart_text
from django.utils.html import escape
from django.utils.safestring import mark_safe
from django.utils.translation import ugettext as _
from django.utils.html import conditional_escape
from xadmin.layout import FormHelper, Layout, Fieldset, Container, Column, Field, Col, TabHolder
from xadmin.util import unquote, lookup_field, display_for_field, boolean_icon, label_for_field

from .base import ModelAdminView, filter_hook, csrf_protect_m

# Text to display within change-list table cells if the value is blank.
EMPTY_CHANGELIST_VALUE = _('Null')


class ShowField(Field):
    template = "xadmin/layout/field_value.html"

    def __init__(self, callback, *args, **kwargs):
        super(ShowField, self).__init__(*args, **kwargs)
        self.results = [(field, callback(field)) for field in self.fields]

    def render(self, form, form_style, context, template_pack=TEMPLATE_PACK, extra_context=None, **kwargs):
        super(ShowField, self).render(form, form_style, context, template_pack, extra_context, **kwargs)
        if extra_context is None:
            extra_context = {}
        if hasattr(self, 'wrapper_class'):
            extra_context['wrapper_class'] = self.wrapper_class

        if self.attrs:
            if 'detail-class' in self.attrs:
                extra_context['input_class'] = self.attrs['detail-class']
            elif 'class' in self.attrs:
                extra_context['input_class'] = self.attrs['class']

        html = ''
        for field, result in self.results:
            extra_context['result'] = result
            if field in form.fields:
                if form.fields[field].widget != forms.HiddenInput:
                    extra_context['field'] = form[field]
                    html += loader.render_to_string(self.template, extra_context)
            else:
                extra_context['field'] = field
                html += loader.render_to_string(self.template, extra_context)
        return html


class ResultField(object):

    def __init__(self, obj, field_name, admin_view=None):
        self.text = '&nbsp;'
        self.wraps = []
        self.allow_tags = False
        self.obj = obj
        self.admin_view = admin_view
        self.field_name = field_name
        self.field = None
        self.attr = None
        self.label = None
        self.value = None

        self.init()

    def init(self):
        self.label = label_for_field(self.field_name, self.obj.__class__,
                                     model_admin=self.admin_view,
                                     return_attr=False
                                     )
        try:
            f, attr, value = lookup_field(
                self.field_name, self.obj, self.admin_view)
        except (AttributeError, ObjectDoesNotExist):
            self.text
        else:
            if f is None:
                self.allow_tags = getattr(attr, 'allow_tags', False)
                boolean = getattr(attr, 'boolean', False)
                if boolean:
                    self.allow_tags = True
                    self.text = boolean_icon(value)
                else:
                    self.text = smart_text(value)
            else:
                if isinstance(f.rel, models.ManyToOneRel):
                    self.text = getattr(self.obj, f.name)
                else:
                    self.text = display_for_field(value, f)
            self.field = f
            self.attr = attr
            self.value = value

    @property
    def val(self):
        text = mark_safe(
            self.text) if self.allow_tags else conditional_escape(self.text)
        if force_text(text) == '' or text == 'None' or text == EMPTY_CHANGELIST_VALUE:
            text = mark_safe(
                '<span class="text-muted">%s</span>' % EMPTY_CHANGELIST_VALUE)
        for wrap in self.wraps:
            text = mark_safe(wrap % text)
        return text


def replace_field_to_value(layout, cb):
    cls_str = str if six.PY3 else basestring
    for i, lo in enumerate(layout.fields):
        if isinstance(lo, Field) or issubclass(lo.__class__, Field):
            layout.fields[i] = ShowField(
                cb, *lo.fields, attrs=lo.attrs, wrapper_class=lo.wrapper_class)
        elif isinstance(lo, cls_str):
            layout.fields[i] = ShowField(cb, lo)
        elif hasattr(lo, 'get_field_names'):
            replace_field_to_value(lo, cb)


class DetailAdminView(ModelAdminView):

    form = forms.ModelForm
    detail_layout = None
    detail_show_all = True
    detail_template = None
    form_layout = None

    def init_request(self, object_id, *args, **kwargs):
        self.obj = self.get_object(unquote(object_id))

        if not self.has_view_permission(self.obj):
            raise PermissionDenied

        if self.obj is None:
            raise Http404(
                _('%(name)s object with primary key %(key)r does not exist.') %
                {'name': force_text(self.opts.verbose_name), 'key': escape(object_id)})
        self.org_obj = self.obj

    @filter_hook
    def get_form_layout(self):
        layout = copy.deepcopy(self.detail_layout or self.form_layout)

        if layout is None:
            layout = Layout(Container(Col('full',
                                          Fieldset(
                                              "", *self.form_obj.fields.keys(),
                                              css_class="unsort no_title"), horizontal=True, span=12)
                                      ))
        elif type(layout) in (list, tuple) and len(layout) > 0:
            if isinstance(layout[0], Column):
                fs = layout
            elif isinstance(layout[0], (Fieldset, TabHolder)):
                fs = (Col('full', *layout, horizontal=True, span=12),)
            else:
                fs = (
                    Col('full', Fieldset("", *layout, css_class="unsort no_title"), horizontal=True, span=12),)

            layout = Layout(Container(*fs))

            if self.detail_show_all:
                rendered_fields = [i[1] for i in layout.get_field_names()]
                container = layout[0].fields
                other_fieldset = Fieldset(_(u'Other Fields'), *[
                                          f for f in self.form_obj.fields.keys() if f not in rendered_fields])

                if len(other_fieldset.fields):
                    if len(container) and isinstance(container[0], Column):
                        container[0].fields.append(other_fieldset)
                    else:
                        container.append(other_fieldset)

        return layout

    @filter_hook
    def get_model_form(self, **kwargs):
        """
        Returns a Form class for use in the admin add view. This is used by
        add_view and change_view.
        """
        if self.exclude is None:
            exclude = []
        else:
            exclude = list(self.exclude)
        if self.exclude is None and hasattr(self.form, '_meta') and self.form._meta.exclude:
            # Take the custom ModelForm's Meta.exclude into account only if the
            # ModelAdmin doesn't define its own.
            exclude.extend(self.form._meta.exclude)
        # if exclude is an empty list we pass None to be consistant with the
        # default on modelform_factory
        exclude = exclude or None
        defaults = {
            "form": self.form,
            "fields": self.fields and list(self.fields) or '__all__',
            "exclude": exclude,
        }
        defaults.update(kwargs)
        return modelform_factory(self.model, **defaults)

    @filter_hook
    def get_form_helper(self):
        helper = FormHelper()
        helper.form_tag = False
        helper.include_media = False
        layout = self.get_form_layout()
        replace_field_to_value(layout, self.get_field_result)
        helper.add_layout(layout)
        cls_str = str if six.PY3 else basestring
        helper.filter(cls_str, max_level=20).wrap(ShowField, admin_view=self)
        return helper

    @csrf_protect_m
    @filter_hook
    def get(self, request, *args, **kwargs):
        form = self.get_model_form()
        self.form_obj = form(instance=self.obj)
        helper = self.get_form_helper()
        if helper:
            self.form_obj.helper = helper

        return self.get_response()

    @filter_hook
    def get_context(self):
        new_context = {
            'title': _('%s Detail') % force_text(self.opts.verbose_name),
            'form': self.form_obj,

            'object': self.obj,

            'has_change_permission': self.has_change_permission(self.obj),
            'has_delete_permission': self.has_delete_permission(self.obj),

            'content_type_id': ContentType.objects.get_for_model(self.model).id,
        }

        context = super(DetailAdminView, self).get_context()
        context.update(new_context)
        return context

    @filter_hook
    def get_breadcrumb(self):
        bcs = super(DetailAdminView, self).get_breadcrumb()
        item = {'title': force_text(self.obj)}
        if self.has_view_permission():
            item['url'] = self.model_admin_url('detail', self.obj.pk)
        bcs.append(item)
        return bcs

    @filter_hook
    def get_media(self):
        return super(DetailAdminView, self).get_media() + self.form_obj.media + \
            self.vendor('xadmin.page.form.js', 'xadmin.form.css')

    @filter_hook
    def get_field_result(self, field_name):

Captian Blog/Blog/templates/blog/article_draft_list.html
{% extends 'base.html' %}
{% load blog_tags %}

{% block main %}
    {% for post in draft_lists %}
        <article class="post post-1">
            <header class="entry-header">
                <h1 class="entry-title">
                    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                </h1>
                <div class="entry-meta">
                    <span class="post-category"><a href="#">{{ post.category }} </a></span>
                    <span class="post-date">
                        <a href="#">
                            <time class="entry-date" datetime="{{ post.created_time }}">
                                {{ post.created }}
                            </time>
                        </a>
                    </span>
                    <span class="post-author"><a href="#">{{ post.author }} </a></span>
                </div>
            </header>
            <div class="entry-content clearfix">
                <p>{{ post.body|markdown|truncatewords_html:50 }}</p>
                <div class="read-more cl-effect-14">
                    <a href="{{ post.get_absolute_url }}" class="more-link">继续阅读 <span
                            class="meta-nav">→</span></a>
                </div>
            </div>
        </article>
    {% empty %}
        <div class="no-post">暂时还没有发布的文章！</div>
    {% endfor %}
{% endblock main %}

Captian Blog/Blog/templates/blog/categroy.html
{% extends 'base.html' %}

{% block main %}
    {% for post in post_list %}
        <article class="post post-1">
            <header class="entry-header">
                <h1 class="entry-title">
                    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                </h1>
                <div class="entry-meta">
                    <span class="post-category"><a href="#">{{ post.category }} </a></span>
                    <span class="post-date">
                        <a href="#">
                            <time class="entry-date" datetime="{{ post.created_time }}">
                                创建时间 {{ post.created }}
                            </time>
                        </a>
                    </span>
                    <span class="post-author"><a href="#">作者 {{ post.author }} </a></span>
                    <span class="comments-link"><a href="{{ post.get_absolute_url }}">评论 ({{post.comments.count}})</a></span>
                </div>
            </header>
            <div class="entry-content clearfix">
                <p>{{ post.abstract }}</p>
                <div class="read-more cl-effect-14">
                    <a href="{{ post.get_absolute_url }}" class="more-link">继续阅读 <span
                            class="meta-nav">→</span></a>
                </div>
            </div>
        </article>
    {% empty %}
        <div class="no-post">暂时还没有发布的文章！</div>
    {% endfor %}
{% endblock main %}

Captian Blog/Blog/templates/blog/categroy_detail.html
{% extends 'base.html' %}
{% load blog_tags %}

{% block main %}

	 {% for article in articles %}
        <article class="post post-1">
            <header class="entry-header">
                <h1 class="entry-title">
                    <a href="{{ article.get_absolute_url }}">{{ article.title }}</a>
                </h1>
                <div class="entry-meta">
                        <a >
                            <time class="entry-date" datetime="{{ article.created_time }}">
                                {{ article.created }}
                            </time>
                        </a>
                    </span>
                    <span class="article-author"><a >{{ article.author }} </a></span>
                    <span class="comments-link">

                    <a>评论({{ article.comments.count }})</a>
                    </span>
                </div>
            </header>
            <div class="entry-content clearfix">
                <p>{{ article.body|markdown|truncatewords_html:50 }}</p>
                <div class="read-more cl-effect-14">
                    <a href="{{ article.get_absolute_url }}" class="more-link">继续阅读 <span
                            class="meta-nav">→</span></a>
                </div>
            </div>
        </article>
    {% empty %}
        <div class="no-post">暂时还没有发布的文章！</div>
    {% endfor %}

 {% endblock main %}

Captian Blog/Blog/templates/blog/detail.html
{% extends 'base.html' %}
{% load blog_tags %}

{% block main %}
    <article class="article post-1">
        <header class="entry-header">
            <h1 class="entry-title">{{ article.title }}</h1>
            <div class="entry-meta">
                <span class="article-category"><a href="#">{{ article.category}} </a></span>
                <span class="article-date">
                    <a href="#">
                    <time class="entry-date" datetime="{{ post.created_time }}">{{ article.created }}</time>
                    </a>
                </span>
                <span class="article-author"><a href="#">{{ article.author }} </a></span>
                <span class="comments-link"><a href="#"> {{ comments.count }} Comments</a></span>
                <span class="comments-link"><a href="{% url 'Blog:edit_article' pk=article.pk %}">编辑</a></span>
                <span class="comments-link"><a href="{% url 'Blog:article_remove' pk=article.pk %}">删除</a></span>
            </div>
        </header>
        <div class="entry-content clearfix">
            {{ article.body|markdown }}
        </div>
    </article>

     <!--添加评论-->
  <!--添加评论的总数-->
 {% with comments.count as total_comments %}  <!--with 标签（tag）允许我们分配一个值给新的变量-->
  <hr><h2>
    {{ total_comments }} 条评论 <!--comment{{ total_comments|pluralize }}-->  <!--使用一个标签显示评论总数-->
  </h2>                                                         <!--total_comments的值，我们使用pluralize 模板（template）过滤器（filter）为单词comment显示复数后缀。-->
{% endwith %}

  <!--加入评论列表-->
{% for comment in comments %}     <!--使用{ for }模板（template）标签（tag）来循环所有的评论-->
  <div class="comment">
    <p class="info">
      #{{ forloop.counter }}楼 {{ comment.comment_time }}  <!--使用 {{ forloop.counter }}变量来枚举所有的评论，在每次迭代中该变量都包含循环计数。并显示评论的用户名-->
      by {{ comment.name }}


    {{ comment.comment_body|markdown}} <!--显示评论的内容:以markdow语法的形式显示-->
  </div>
{% empty %}                     <!--如果comments列为空我们会显示一个默认的信息-->
  <p>还无任何评论，欢迎点评.</p> <!--告诉我们的用户这篇帖子还没有任何评论。-->
{% endfor %}


    <!--表单提交成功后,你需要渲染表单或者显示一条成功的信息来代替之前的内容-->
{% if new_comment %}                                <!--如果new_comment对象存在-->
  <h2>评论已提交成功.</h2>             <!--提示一条已经添加的信息提示-->
{% else %}                                          <!--否则-->
  <h2>添加评论</h2>                        <!--用段落<p>元素渲染表单中每一个字段，并且包含POST请求需要的CSRF令牌。-->
  <form action="." method="post">
    {{ comment_form.as_p }}
    {% csrf_token %}
    <p><input type="submit" value="提交评论"></p>
  </form>
{% endif %}

{% endblock main %}

Captian Blog/Blog/templates/blog/edit_article.html
{% block content %}
  <p>项目添加新内容</p>
  <form action="{% url 'Blog:edit_article' pk=article.pk %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button name='submit'>提交</button>
  </form>

{% endblock content %}

Captian Blog/Blog/templates/blog/index.html
{% extends 'base.html' %}
{% load blog_tags %}

{% block main %}
    {% for post in post_list %}
        <article class="post post-1">
            <header class="entry-header">
                <h1 class="entry-title">
                    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                </h1>
                <div class="entry-meta">
                    <span class="post-category"><a href="#">{{ post.category }} </a></span>
                    <span class="post-date">
                        <a href="#">
                            <time class="entry-date" datetime="{{ post.created_time }}">
                                {{ post.created }}
                            </time>
                        </a>
                    </span>
                    <span class="post-author"><a href="#">{{ post.author }} </a></span>
                    <span class="comments-link">
                    <a href="{{ post.get_absolute_url }}">评论({{ post.comments.count }})</a>
                    </span>
                </div>
            </header>
            <div class="entry-content clearfix">
                <p>{{ post.body|markdown|truncatewords_html:5 }}</p>
                <div class="read-more cl-effect-14">
                    <a href="{{ post.get_absolute_url }}" class="more-link">继续阅读 <span
                            class="meta-nav">→</span></a>
                </div>
            </div>
        </article>
    {% empty %}
        <div class="no-post">暂时还没有发布的文章！</div>
    {% endfor %}
{% endblock main %}

Captian Blog/Blog/templates/blog/new_Article.html
{% block content %}
<P>New post</p>

{% if new_comment %}
  <h2>提交成功.</h2>
{% else %}
    <form action="{% url 'Blog:new_article' %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
{% endif %}
{% endblock content %}