Captian Blog/Blog/urls.py
#!/usr/bin/python
# -*- coding:utf-8 -*-
from django.conf.urls import url, include
from . import views

urlpatterns = [
    # 主页
    url(r'^$', views.index, name='index'),
    # 详情页
    url(r'^post/(?P<pk>[0-9]+)/$', views.detail, name='detail'),
    #文章归档
    url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.Archives, name='Archives'),
    #文章主题
    url(r'^category/(?P<pk>[0-9]+)/$', views.categroy_detail, name='category'),
    # 写文章
    url(r'^new_article/$', views.new_article, name='new_article'),
    #文章草稿箱
    url(r'^drafts/$', views.article_draft_list, name='article_draft_list'),
    #编辑文章
    url(r'^edit_article/(?P<pk>[0-9]+)/$', views.edit_article, name='edit_article'),
    #删除文章
    url(r'^article_remove/(?P<pk>[0-9]+)/$', views.article_remove, name='article_remove'),
    #全文搜索
    url(r'^search/', include('haystack.urls')),
]

Captian Blog/Web/urls.py
#!/usr/bin/python
# -*- coding:utf-8 -*-
"""Web URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.10/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url, include
#from django.contrib import admin
from extra_apps import xadmin


urlpatterns = [
    #url(r'^admin/', admin.site.urls),
    url(r'^xadmin/', include(xadmin.site.urls), name='xadmin'),
    url(r'^user/', include('user.urls', namespace='user')),
    url(r'', include('Blog.urls', namespace='Blog')),
]

Captian Blog/Blog/models.py
# -*- coding:utf-8 -*-

from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils import timezone

class Categroy(models.Model):
	'''文章分类'''
	theme = models.CharField('文章分类',max_length=10)
	created = models.DateTimeField('创建时间',auto_now_add=True)

	class Meta:
		ordering =('-created',)
		verbose_name_plural = '文章分类'

	def __str__(self):
		return self.theme


class Article(models.Model):
	'''标题'''
	categroy = models.ForeignKey(Categroy,verbose_name='分类', on_delete=models.CASCADE)
	STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
        ('personal','Personal'),
    )
	title = models.CharField('标题',max_length=70)
	created = models.DateTimeField('创建时间', auto_now_add=True)
	updated = models.DateTimeField('更新时间', auto_now=True)
	status = models.CharField('文章状态', max_length=10, choices=STATUS_CHOICES, default='draft')
	author = models.ForeignKey(User,verbose_name='作者')
	slug = models.SlugField('标签', max_length=250, unique_for_date='created')
	body = models.TextField('正文')
	topped = models.BooleanField('置顶', default=False)
	views = models.PositiveIntegerField('浏览量', default=0)
	likes = models.PositiveIntegerField('点赞数', default=0)
	abstract = models.CharField('摘要', max_length=7, blank=True, null=True,
                                help_text="可选，如若为空将摘取正文的前54个字符")
	#此功能暂时无法实现


	class Meta:
		ordering = ('-created',)
		verbose_name_plural = '文章'
	def __str__(self):
		return self.title
	def get_absolute_url(self):
		return reverse('Blog:detail', kwargs={'pk': self.pk})


class Comments(models.Model):
	'''评论管理'''
	article = models.ForeignKey(Article, verbose_name='文章评论',related_name='comments')
	comment_body = models.TextField('评论内容')
	comment_time = models.DateTimeField('评论时间',auto_now=True)
	name = models.CharField('昵称',max_length=10)
	active = models.BooleanField(default=True)
	#comment_response = models.TextField('评论回复')
	#comment_like = models.PositiveIntegerField('点赞数', default=0)

	class Meta:
		ordering = ('comment_time',)
		verbose_name_plural = '评论管理'

	def __str__(self):
		 return 'Comment by {} on {}'.format(self.name, self.article)

Captian Blog/Blog/forms.py
from django import forms
from .models import Comments, Article


class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ['categroy', 'title', 'body', 'status', 'topped']


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comments
        fields = ['name','comment_body']

Captian Blog/Blog/views.py
#!/usr/bin/python
# -*- coding:utf-8 -*-
from Blog.models import Article ,Comments ,Categroy
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404
from django.db.models import Count
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from .forms import ArticleForm, CommentForm
import markdown


def index(request):
    """
    主页信息返回
    """
    post_list = Article.objects.filter(status='published')
    return render(request, 'blog/index.html',context={'post_list': post_list})


def article_draft_list(request):
    '''文章草稿箱'''
    draft_lists = Article.objects.filter(status='draft').order_by('-created')
    context = {'draft_lists': draft_lists}
    return render(request, 'blog/article_draft_list.html', context)


def Archives(request,year,month):
    post_list = Article.objects.filter(created__year=year,
                                        created__month=month,)
    return render(request, 'blog/index.html', context= {'post_list': post_list})


def Category(request, pk):
    """
    显示对应主题所有文章
    """
    cate = get_object_or_404(Category, pk=pk)
    post_list = Categroy.objects.filter(theme=cate).filter(status='published')
    context={'post_list': post_list}
    return render(request, 'blog/index.html', context)


def categroy_detail(request, pk):
    '''分类标签文章详情'''
    article_list = Categroy.objects.get(pk=pk)
    articles = article_list.article_set.filter(status='published').order_by('-created')
    context = {'article_list': article_list,'articles': articles}

    return render(request, 'blog/categroy_detail.html', context )


def detail(request, pk):
    """
    文章详情页
    """
    article = get_object_or_404(Article, pk=pk)
    body = Article.objects.get(pk=pk)
    ''' 添加评论'''
    comments = article.comments.filter(active=True)
    #添加了一个查询集（QuerySet）来获取这个帖子所有有效的评论，通过参数过滤所有已经发布过的
    new_comment = None
    # 定义一个变量名为new_comment 及为新的评论 为 空

    if request.method == 'POST':
         # 如果是通过POST请求，我们使用提交的数据新建一条评论
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # 用is_valid()方法验证这些数据去实例化表单，如果表单通过验证，我们会做以下的操作：
            new_comment = comment_form.save(commit=False)
            '''
            通过调用表单的save()方法创建一个新的Comment对象，参数执行使对象无法立即保存到数据库中。
            注意save()方法是给ModelForm用的，而不是给Form实例用的
            '''
            new_comment.article = article
             #为刚创建的评论分配到当前的帖子
            new_comment.save()
            # 再次执行保存，这次是保存到数据库中的
    else:
        #通过GET请求被加载的，那么我们用comment_fomr = commentForm()来创建一个表单实例。
        comment_form = CommentForm()
    return render(request, 'blog/detail.html',
                    {
                    'article': article,
                    'comments': comments,
                    'body': body,
                    'comment_form': comment_form})


def new_article(request):
    '''写文章'''
    if request.method != "POST":
        form = ArticleForm()
    else:
        form = ArticleForm(data=request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            #提交后跳转到index页面
            return HttpResponseRedirect(reverse('Blog:index'))
    context = {'form': form}
    return render(request, 'blog/new_article.html', context)


def edit_article(request, pk):
    '''编辑文章'''
    article = get_object_or_404(Article, pk=pk)
    body = Article.objects.get(pk=pk)

    if request.method != "POST":
        form = ArticleForm(instance=body)
    else:
        form = ArticleForm(instance=body, data=request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            #提交后跳转到index页面
            return HttpResponseRedirect(reverse('Blog:index'))

    context = {'article': article, 'form': form}
    return render(request, 'blog/edit_article.html', context)


def article_remove(request, pk):
    article = get_object_or_404(Article, pk=pk)
    article.delete()
    return HttpResponseRedirect(reverse('Blog:index'))

Captian Blog/Blog/templates/base.html
<!DOCTYPE html>

<html>
<head>
    <title>Black &amp; White</title>

    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    {% load staticfiles %}
    <!-- css -->
    <link rel="stylesheet" href="{% static 'blog/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="{% static 'blog/css/pace.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/custom.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/friendly.css' %}">
    <!-- js -->
    <script src="{% static 'blog/js/jquery-2.1.3.min.js' %}"></script>
    <script src="{% static 'blog/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'blog/js/pace.min.js' %}"></script>
    <script src="{% static 'blog/js/modernizr.custom.js' %}"></script>
</head>

<body>
<div class="container">
    <header id="site-header">
        <div class="row">
            <div class="col-md-4 col-sm-5 col-xs-8">
                <div class="logo">
                    <h1><a href="index.html"><b>Django</b> &amp; Blog</a></h1>
                </div>
            </div><!-- col-md-4 -->
            <div class="col-md-8 col-sm-7 col-xs-4">
                <nav class="main-nav" role="navigation">
                    <div class="navbar-header">
                        <button type="button" id="trigger-overlay" class="navbar-toggle">
                            <span class="ion-navicon"></span>
                        </button>
                    </div>

                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav navbar-right">
                            <li class="cl-effect-11"><a href="index.html" data-hover="Home">Home</a></li>
                            <li class="cl-effect-11"><a href="full-width.html" data-hover="Blog">Blog</a></li>
                            <li class="cl-effect-11"><a href="about.html" data-hover="About">About</a></li>
                            <li class="cl-effect-11"><a href="contact.html" data-hover="Contact">Contact</a></li>
                            <li class="cl-effect-11"><a href="{% url 'Blog:new_article' %}" data-hover="New article">New article</a></li>
                            <li class="cl-effect-11"><a href="{% url 'Blog:article_draft_list' %}" data-hover="草稿">草稿</a></li>
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </nav>
                <div id="header-search-box">
                    <a id="search-menu" href="search"><span id="search-icon" class="ion-ios-search-strong"></span></a>
                    <div id="search-form" class="search-form">
                        <form role="search" method="get" id="searchform" action="#">
                            <input type="search" placeholder="Search" required>
                            <button type="submit"><span class="ion-ios-search-strong"></span></button>
                        </form>
                    </div>
                </div>
            </div><!-- col-md-8 -->
        </div>
    </header>
</div>

<div class="content-body">
    <div class="container">
        <div class="row">
            <main class="col-md-8">
                {% block main %}
                {% endblock main %}

             <!--侧边栏显示-->
            </main>
            {% load blog_tags %}
            <aside class="col-md-4">
                <!--最新文章-->
                <div class="widget widget-recent-article">
                    <h3 class="widget-title">最新文章</h3>
                    {% get_recent_posts as recent_post_list %}
                    <ul>
                        {% for post in recent_post_list %}
                            <li>
                                <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
                <!--按日期归档-->
                <div class="widget widget-archives">
                    <h3 class="widget-title">归档</h3>
                    {% archives as date_list %}
                    <ul>
                        {% for date in date_list %}
                            <li>
                                <a href="{% url 'Blog:Archives' date.year date.month %}">
                                    {{ date.year }} 年 {{ date.month }} 月
                                </a>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
                <!--按主题分类-->
                <div class="widget widget-category">
                    <h3 class="widget-title">分类</h3>
                    {% get_categories as category_list %}
                    <ul>
                        {% for category in category_list %}
                            <li>
                                <a href="{% url 'Blog:category' category.pk %}">{{ category.theme }}
                                (<small>{{ category.article_set.count }}</small>)</a>
                            </li>
                        {% endfor %}
                    </ul>
                </div>

                <!--显示评论最多的帖子-->
                <div class="widget widget-category">
                    <h3 class="widget-title">热点文章</h3>
                    {% get_most_commented_articles as most_commented_articles  %}
                    <ul>
                        {% for article in most_commented_articles %}
                            <li>
                                <a href="{{ article.get_absolute_url }}">{{ article.title }} </a>
                            </li>
                        {% endfor %}
                    </ul>
                </div>

            </aside>
        </div>
    </div>
</div>
<footer id="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p class="copyright">&copy; <a>Copyright 2017 Develope by Django-Web Team</a></p>
            </div>
        </div>
    </div>
</footer>




<!-- Mobile Menu -->
<div class="overlay overlay-hugeinc">
    <button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
    <nav>
        <ul>
            <li><a href="index.html">Home</a></li>
            <li><a href="full-width.html">Blog</a></li>
            <li><a href="about.html">About</a></li>
            <li><a href="contact.html">Contact</a></li>
        </ul>
    </nav>
</div>

<script src="js/script.js"></script>

</body>
</htm>